apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: emojivoto-mapping
  namespace: emojivoto
spec:
  host: test.mturner.k736.net
  precedence: 1
  prefix: /
  service: web-svc.emojivoto.svc.cluster.local:80
