#dev-rel-01
#uid=6089b281-4f97-4b82-a891-937a8af8b873
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWakNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFl5TlRnMU16RTVNakFlRncweU1UQTNNRGt4TnpVek1USmFGdzB6TVRBM01EY3hOelV6TVRKYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFl5TlRnMU16RTVNakJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQklEM1RVbnF4T0tFZTUzVUlGcVljbDJ5a1d1ZEgzcFdZYmM3ZHBMQTNQY2EKdFMrSjVoM3ppcHpZZ0Y0QlM5cTlmWFB2d0dBTDNxbkZZVnNMMjM4YWxhV2pJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUFkL3pabkk2V0srCmpSSWx5TUl1UVEyeldCYnRQZXEzWTc3Z2JFcFJlRkJnQWlCN2FLVnZtRjl3Tnd2ZWlwYTRmVUxhVTJkVEhORTgKVUFUVDhCZ25rVXpMSGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://35.194.43.253
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: 1c1f430d0aa5843e8a1126efe66f33d0
    username: admin
